graph/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitor.urls')), # ホームURL
    path('accounts/', include('django.contrib.auth.urls')), # ログイン認証
]

monitor/urls.py
from django.urls import path
from . import views

app_name = 'monitor'

urlpatterns = [
    # トップ画面
    path('', views.IndexView.as_view(), name='index'),

    # 詳細画面
    path('monitor/<int:pk>/', views.DetailView.as_view(), name='detail'),

    # グラフ描画
    path('monitor/<int:pk>/plot/', views.get_svg, name='plot'),

    # 500エラー確認用
    path('test/', views.my_test_500_view, name='test'),

    # ファイルアップロード用
    path('monitor/upload/', views.upload, name='upload'),
    path('monitor/upload_complete/', views.upload_complete, name='upload_complete'),
]

monitor/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime as dt


class Location(models.Model):
    """場所モデル"""
    class Meta:
        db_table = 'location'

    name = models.CharField(verbose_name='ロケーション名', max_length=255)
    memo = models.CharField(verbose_name='メモ', max_length=255, default='', blank=True)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url(self):
        return reverse('monitor:index')


class WeatherData(models.Model):
    """気象データモデル"""
    class Meta:
        db_table = 'weather_data'
        unique_together = (('location', 'data_datetime'),)

    location = models.ForeignKey(Location, verbose_name='ロケーション', on_delete=models.PROTECT)
    data_datetime = models.DateTimeField(verbose_name='データ日時', default=dt.strptime('2001-01-01 00:00:00', '%Y-%m-%d %H:%M:%S'))
    temperature = models.FloatField(verbose_name='気温')
    humidity = models.FloatField(verbose_name='湿度')
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.location.name + ":" + str(self.data_datetime)

monitor/forms.py
from django import forms
import os

VALID_EXTENSIONS = ['.csv']


class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='アップロードファイル',
    )

    def clean_file(self):
        file = self.cleaned_data['file']
        extension = os.path.splitext(file.name)[1] # 拡張子を取得
        if not extension.lower() in VALID_EXTENSIONS:
            raise forms.ValidationError('csvファイルを選択してください！')

monitor/views.py
from django.http import HttpResponse
from django.views import generic
from .models import Location, WeatherData
from django.contrib.auth.mixins import LoginRequiredMixin
import io
import matplotlib.pyplot as plt
import logging
from django.http import HttpResponseServerError
from django.shortcuts import render, redirect
import os
from .forms import UploadFileForm
from monitor import addCsv

UPLOAD_DIR = os.path.dirname(os.path.abspath(__file__)) + '/uploads/'  # アップロードしたファイルを保存するディレクトリ

logger = logging.getLogger('development')


class IndexView(LoginRequiredMixin, generic.ListView):
    model = Location
    paginate_by = 5
    ordering = ['-updated_at']
    template_name = 'monitor/index.html'


class DetailView(generic.DetailView):
    model = Location
    template_name = 'monitor/detail.html'


def my_test_500_view(request):
    # Return an "Internal Server Error" 500 response code.
    return HttpResponseServerError


# グラフ作成
def setPlt(pk):
    # 折れ線グラフを出力

    weather_data = WeatherData.objects.select_related('location').filter(location_id=pk)  # 対象ロケーションの気象データを取得
    # weather_data = WeatherData.objects.raw('SELECT * FROM weather_data WHERE location_id = %s', str(pk)) # このクエリでもOK
    x = [data.data_datetime for data in weather_data] # 日時
    y1 = [data.temperature for data in weather_data] # 気温
    y2 = [data.humidity for data in weather_data]  # 湿度
    """
    # 横に3つのグラフを並べる：axes([左, 下, 幅, 高さ])
    plt.axes([0.5, 0.5, 1.0, 1.0])  # 1つ目のグラフ
    plt.plot(x, y1, x, y2)

    plt.axes([1.7, 0.5, 1.0, 1.0])  # 2つ目のグラフ
    plt.plot(x, y1)

    plt.axes([2.9, 0.5, 1.0, 1.0])  # 3つ目のグラフ
    plt.plot(x, y2)
   """
    """
    # 縦に3つのグラフを並べる：axes([左, 下, 幅, 高さ])
    plt.axes([0.5, 2.4, 1.0, 1.0])  # 1つ目のグラフ
    plt.plot(x, y1, x, y2)
    
    plt.axes([0.5, 1.2, 1.0, 1.0])  # 2つ目のグラフ
    plt.plot(x, y1)
    
    plt.axes([0.5, 0.0, 1.0, 1.0])  # 3つ目のグラフ
    plt.plot(x, y2)
   """

    # 2×2のレイアウトに配置する
    fig = plt.figure(figsize=(15, 10))
    row = 2
    col = 2

    fig.add_subplot(row, col, 1)
    plt.plot(x, y1, x, y2)

    fig.add_subplot(row, col, 3)
    plt.plot(x, y1)

    fig.add_subplot(row, col, 4)
    plt.plot(x, y2)


# svgへの変換
def pltToSvg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s


def get_svg(request, pk):
    setPlt(pk)  # create the plot
    svg = pltToSvg()  # convert plot to SVG
    plt.cla()  # clean up plt so it can be re-used
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response


# アップロードされたファイルのハンドル
def handle_uploaded_file(f):
    path = os.path.join(UPLOAD_DIR, f.name)
    with open(path, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    try:
        addCsv.insert_csv_data(path)  # csvデータをDBに登録する
    except Exception as exc:
        logger.error(exc)

    os.remove(path)  # アップロードしたファイルを削除


# ファイルアップロード
def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return redirect('monitor:upload_complete')  # アップロード完了画面にリダイレクト
    else:
        form = UploadFileForm()
    return render(request, 'monitor/upload.html', {'form': form})


# ファイルアップロード完了
def upload_complete(request):
    return render(request, 'monitor/upload_complete.html')

monitor/templates/monitor/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <section class="">
        {{ object.memo|linebreaksbr }}
    </section>

    <img src='{% url 'monitor:plot' object.pk %}' width=1200 height=800>

    <section>
        <p><a href="javascript:history.back()">&lt; Back</a></p>
    </section>
{% endblock %}

monitor/templates/monitor/index.html
{% extends 'base.html' %}

{% block content %}

<h1>My Locations</h1>

<section class="">
    <ul>
        {% for location in object_list %}
        <li>
            <h2><a href="{% url 'monitor:detail' location.pk %}">{{ location.name }}</a></h2>
            <p>{{ location.memo }}</p>
        </li>
        {% empty %}
        <li class="no-post">
            <p>No location yet.</p>
        {% endfor %}
    </ul>
</section>

{% if is_paginated %}
<section class="pagination">
    <ul>
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
            {% else %}
            &lt;&lt; Prev
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
            {% else %}
            Next &gt;&gt;
            {% endif %}
        </li>
    </ul>
</section>
{% endif %}
{% endblock %}

monitor/templates/monitor/upload.html
{% extends 'base.html' %}

{% block content %}

<h1>アップロード サンプル</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button type="submit">アップロード</button>
    </div>
</form>

{% endblock %}

monitor/templates/monitor/upload_complete.html
{% extends 'base.html' %}

{% block content %}

<h1>アップロード完了</h1>

<a href="{% url 'monitor:upload' %}"><button>戻る</button></a>

{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Weather Monitor</title>
    </head>
    <body>
    <div class="container">
        <header>
            <p class="site-name"><a href="{% url 'monitor:index' %}">Weather Monitor</a></p>
            <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class="logout">ログアウト</a></li>
                    <li><a href="{% url 'monitor:upload' %}">ファイルアップロード</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}" class="login">ログイン</a></li>
                {% endif %}
            </ul>
        </nav>
        </header>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    </body>
</html>